---
- name: Install epel-release
  become: true
  ansible.builtin.yum:
    name: epel-release
    state: present
  tags: nginx
- name: Install Nginx
  become: true
  ansible.builtin.yum:
    name: nginx
    state: present
  notify: start-nginx
  tags: nginx 
- name: Create directory
  become: true
  file:
    state: directory
    dest: "/etc/nginx"
    mode: "0755"
  tags: nginx
- name: Create Nginx config file
  become: true
  template:
    src: "templates/nginx.conf.j2"
    dest: "/etc/nginx/nginx.conf"
    mode: "0644"
  notify: reload-nginx
  tags: nginx
- name: Install git package
  become: true
  ansible.builtin.yum:
    name: git
    state: present
- name: Copy package from git 
  git:
    repo: "{{ lighthouse_url }}"
    version: master
    dest: "{{ lighthouse_dir }}"
  tags: lighthouse
- name: Create lighthouse config
  become: true
  template:
    src: "templates/lighthouse.conf.j2"
    dest: "/etc/nginx/conf.d/default.conf"
    mode: "0644"
  notify: reload-nginx
  tags: lighthouse